"""store complete bootstrap schema and prediction tables

Revision ID: 122f67888406
Revises: 0001_initial_schema
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '122f67888406'
down_revision: Union[str, Sequence[str], None] = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('start_event', sa.Integer(), nullable=True),
    sa.Column('stop_event', sa.Integer(), nullable=True),
    sa.Column('chip_type', sa.String(length=20), nullable=True),
    sa.Column('overrides', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False, server_default='{}'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('element_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('singular_name', sa.String(length=50), nullable=False),
    sa.Column('plural_name', sa.String(length=50), nullable=False),
    sa.Column('singular_name_short', sa.String(length=10), nullable=False),
    sa.Column('squad_select', sa.Integer(), nullable=True),
    sa.Column('squad_min_play', sa.Integer(), nullable=True),
    sa.Column('squad_max_play', sa.Integer(), nullable=True),
    sa.Column('ui_shorthand', sa.String(length=10), nullable=True),
    sa.Column('sub_positions_locked', sa.JSON(), nullable=True),
    sa.Column('element_count', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False, server_default='{}'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_event', sa.Integer(), nullable=False),
    sa.Column('stop_event', sa.Integer(), nullable=False),
    sa.Column('highest_score', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False, server_default='{}'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('feature_version', sa.String(length=50), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_start_event', sa.Integer(), nullable=True),
    sa.Column('training_end_event', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_run_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('predicted_points', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('predicted_minutes', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('lower_bound', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('upper_bound', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['prediction_run_id'], ['prediction_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_run_id', 'player_id', 'event_id')
    )
    op.create_index(op.f('ix_player_predictions_event_id'), 'player_predictions', ['event_id'], unique=False)
    op.create_index(op.f('ix_player_predictions_player_id'), 'player_predictions', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_predictions_prediction_run_id'), 'player_predictions', ['prediction_run_id'], unique=False)
    op.add_column('events', sa.Column('release_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('average_entry_score', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('finished', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('data_checked', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('highest_scoring_entry', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('deadline_time_epoch', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('deadline_time_game_offset', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('highest_score', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('is_previous', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('is_current', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('is_next', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('cup_leagues_created', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('h2h_ko_matches_created', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('can_enter', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('can_manage', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('released', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('ranked_count', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('most_selected', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('most_transferred_in', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('top_element', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('transfers_made', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('most_captained', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('most_vice_captained', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('overrides', sa.JSON(), nullable=True))
    op.add_column('events', sa.Column('chip_plays', sa.JSON(), nullable=True))
    op.add_column('events', sa.Column('top_element_info', sa.JSON(), nullable=True))
    op.add_column('events', sa.Column('raw_data', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('fixtures', sa.Column('raw_data', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('players', sa.Column('can_transact', sa.Boolean(), nullable=True))
    op.add_column('players', sa.Column('can_select', sa.Boolean(), nullable=True))
    op.add_column('players', sa.Column('chance_of_playing_next_round', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('chance_of_playing_this_round', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('code', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('cost_change_event', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('cost_change_event_fall', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('cost_change_start', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('cost_change_start_fall', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('dreamteam_count', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('element_type', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('ep_next', sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column('players', sa.Column('ep_this', sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column('players', sa.Column('event_points', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('form', sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column('players', sa.Column('in_dreamteam', sa.Boolean(), nullable=True))
    op.add_column('players', sa.Column('news', sa.Text(), nullable=True))
    op.add_column('players', sa.Column('news_added', sa.DateTime(timezone=True), nullable=True))
    op.add_column('players', sa.Column('now_cost', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('photo', sa.String(length=100), nullable=True))
    op.add_column('players', sa.Column('points_per_game', sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column('players', sa.Column('removed', sa.Boolean(), nullable=True))
    op.add_column('players', sa.Column('selected_by_percent', sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column('players', sa.Column('special', sa.Boolean(), nullable=True))
    op.add_column('players', sa.Column('squad_number', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('status', sa.String(length=5), nullable=True))
    op.add_column('players', sa.Column('team_code', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('total_points', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('transfers_in', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('transfers_in_event', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('transfers_out', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('transfers_out_event', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('value_form', sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column('players', sa.Column('value_season', sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column('players', sa.Column('region', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('team_join_date', sa.Date(), nullable=True))
    op.add_column('players', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('players', sa.Column('has_temporary_code', sa.Boolean(), nullable=True))
    op.add_column('players', sa.Column('opta_code', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('minutes', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('goals_scored', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('assists', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('clean_sheets', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('goals_conceded', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('own_goals', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('penalties_saved', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('penalties_missed', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('yellow_cards', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('red_cards', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('saves', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('bonus', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('bps', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('influence', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('players', sa.Column('creativity', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('players', sa.Column('threat', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('players', sa.Column('ict_index', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('players', sa.Column('clearances_blocks_interceptions', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('recoveries', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('tackles', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('defensive_contribution', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('starts', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('expected_goals', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('players', sa.Column('expected_assists', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('players', sa.Column('expected_goal_involvements', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('players', sa.Column('expected_goals_conceded', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('players', sa.Column('influence_rank', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('influence_rank_type', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('creativity_rank', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('creativity_rank_type', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('threat_rank', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('threat_rank_type', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('ict_index_rank', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('ict_index_rank_type', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('corners_and_indirect_freekicks_order', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('corners_and_indirect_freekicks_text', sa.Text(), nullable=True))
    op.add_column('players', sa.Column('direct_freekicks_order', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('direct_freekicks_text', sa.Text(), nullable=True))
    op.add_column('players', sa.Column('penalties_order', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('penalties_text', sa.Text(), nullable=True))
    op.add_column('players', sa.Column('expected_goals_per_90', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('players', sa.Column('saves_per_90', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('players', sa.Column('expected_assists_per_90', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('players', sa.Column('expected_goal_involvements_per_90', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('players', sa.Column('expected_goals_conceded_per_90', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('players', sa.Column('goals_conceded_per_90', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('players', sa.Column('now_cost_rank', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('now_cost_rank_type', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('form_rank', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('form_rank_type', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('points_per_game_rank', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('points_per_game_rank_type', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('selected_rank', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('selected_rank_type', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('starts_per_90', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('players', sa.Column('clean_sheets_per_90', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('players', sa.Column('defensive_contribution_per_90', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('players', sa.Column('raw_data', sa.JSON(), nullable=False, server_default='{}'))
    op.create_index(op.f('ix_players_element_type'), 'players', ['element_type'], unique=False)
    op.add_column('teams', sa.Column('code', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('draw', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('form', sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column('teams', sa.Column('loss', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('played', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('strength', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('team_division', sa.String(length=100), nullable=True))
    op.add_column('teams', sa.Column('unavailable', sa.Boolean(), nullable=True))
    op.add_column('teams', sa.Column('win', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('strength_overall_home', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('strength_overall_away', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('strength_attack_home', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('strength_attack_away', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('strength_defence_home', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('strength_defence_away', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('pulse_id', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('raw_data', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'raw_data')
    op.drop_column('teams', 'pulse_id')
    op.drop_column('teams', 'strength_defence_away')
    op.drop_column('teams', 'strength_defence_home')
    op.drop_column('teams', 'strength_attack_away')
    op.drop_column('teams', 'strength_attack_home')
    op.drop_column('teams', 'strength_overall_away')
    op.drop_column('teams', 'strength_overall_home')
    op.drop_column('teams', 'win')
    op.drop_column('teams', 'unavailable')
    op.drop_column('teams', 'team_division')
    op.drop_column('teams', 'strength')
    op.drop_column('teams', 'position')
    op.drop_column('teams', 'points')
    op.drop_column('teams', 'played')
    op.drop_column('teams', 'loss')
    op.drop_column('teams', 'form')
    op.drop_column('teams', 'draw')
    op.drop_column('teams', 'code')
    op.drop_index(op.f('ix_players_element_type'), table_name='players')
    op.drop_column('players', 'raw_data')
    op.drop_column('players', 'defensive_contribution_per_90')
    op.drop_column('players', 'clean_sheets_per_90')
    op.drop_column('players', 'starts_per_90')
    op.drop_column('players', 'selected_rank_type')
    op.drop_column('players', 'selected_rank')
    op.drop_column('players', 'points_per_game_rank_type')
    op.drop_column('players', 'points_per_game_rank')
    op.drop_column('players', 'form_rank_type')
    op.drop_column('players', 'form_rank')
    op.drop_column('players', 'now_cost_rank_type')
    op.drop_column('players', 'now_cost_rank')
    op.drop_column('players', 'goals_conceded_per_90')
    op.drop_column('players', 'expected_goals_conceded_per_90')
    op.drop_column('players', 'expected_goal_involvements_per_90')
    op.drop_column('players', 'expected_assists_per_90')
    op.drop_column('players', 'saves_per_90')
    op.drop_column('players', 'expected_goals_per_90')
    op.drop_column('players', 'penalties_text')
    op.drop_column('players', 'penalties_order')
    op.drop_column('players', 'direct_freekicks_text')
    op.drop_column('players', 'direct_freekicks_order')
    op.drop_column('players', 'corners_and_indirect_freekicks_text')
    op.drop_column('players', 'corners_and_indirect_freekicks_order')
    op.drop_column('players', 'ict_index_rank_type')
    op.drop_column('players', 'ict_index_rank')
    op.drop_column('players', 'threat_rank_type')
    op.drop_column('players', 'threat_rank')
    op.drop_column('players', 'creativity_rank_type')
    op.drop_column('players', 'creativity_rank')
    op.drop_column('players', 'influence_rank_type')
    op.drop_column('players', 'influence_rank')
    op.drop_column('players', 'expected_goals_conceded')
    op.drop_column('players', 'expected_goal_involvements')
    op.drop_column('players', 'expected_assists')
    op.drop_column('players', 'expected_goals')
    op.drop_column('players', 'starts')
    op.drop_column('players', 'defensive_contribution')
    op.drop_column('players', 'tackles')
    op.drop_column('players', 'recoveries')
    op.drop_column('players', 'clearances_blocks_interceptions')
    op.drop_column('players', 'ict_index')
    op.drop_column('players', 'threat')
    op.drop_column('players', 'creativity')
    op.drop_column('players', 'influence')
    op.drop_column('players', 'bps')
    op.drop_column('players', 'bonus')
    op.drop_column('players', 'saves')
    op.drop_column('players', 'red_cards')
    op.drop_column('players', 'yellow_cards')
    op.drop_column('players', 'penalties_missed')
    op.drop_column('players', 'penalties_saved')
    op.drop_column('players', 'own_goals')
    op.drop_column('players', 'goals_conceded')
    op.drop_column('players', 'clean_sheets')
    op.drop_column('players', 'assists')
    op.drop_column('players', 'goals_scored')
    op.drop_column('players', 'minutes')
    op.drop_column('players', 'opta_code')
    op.drop_column('players', 'has_temporary_code')
    op.drop_column('players', 'birth_date')
    op.drop_column('players', 'team_join_date')
    op.drop_column('players', 'region')
    op.drop_column('players', 'value_season')
    op.drop_column('players', 'value_form')
    op.drop_column('players', 'transfers_out_event')
    op.drop_column('players', 'transfers_out')
    op.drop_column('players', 'transfers_in_event')
    op.drop_column('players', 'transfers_in')
    op.drop_column('players', 'total_points')
    op.drop_column('players', 'team_code')
    op.drop_column('players', 'status')
    op.drop_column('players', 'squad_number')
    op.drop_column('players', 'special')
    op.drop_column('players', 'selected_by_percent')
    op.drop_column('players', 'removed')
    op.drop_column('players', 'points_per_game')
    op.drop_column('players', 'photo')
    op.drop_column('players', 'now_cost')
    op.drop_column('players', 'news_added')
    op.drop_column('players', 'news')
    op.drop_column('players', 'in_dreamteam')
    op.drop_column('players', 'form')
    op.drop_column('players', 'event_points')
    op.drop_column('players', 'ep_this')
    op.drop_column('players', 'ep_next')
    op.drop_column('players', 'element_type')
    op.drop_column('players', 'dreamteam_count')
    op.drop_column('players', 'cost_change_start_fall')
    op.drop_column('players', 'cost_change_start')
    op.drop_column('players', 'cost_change_event_fall')
    op.drop_column('players', 'cost_change_event')
    op.drop_column('players', 'code')
    op.drop_column('players', 'chance_of_playing_this_round')
    op.drop_column('players', 'chance_of_playing_next_round')
    op.drop_column('players', 'can_select')
    op.drop_column('players', 'can_transact')
    op.drop_column('fixtures', 'raw_data')
    op.drop_column('events', 'raw_data')
    op.drop_column('events', 'top_element_info')
    op.drop_column('events', 'chip_plays')
    op.drop_column('events', 'overrides')
    op.drop_column('events', 'most_vice_captained')
    op.drop_column('events', 'most_captained')
    op.drop_column('events', 'transfers_made')
    op.drop_column('events', 'top_element')
    op.drop_column('events', 'most_transferred_in')
    op.drop_column('events', 'most_selected')
    op.drop_column('events', 'ranked_count')
    op.drop_column('events', 'released')
    op.drop_column('events', 'can_manage')
    op.drop_column('events', 'can_enter')
    op.drop_column('events', 'h2h_ko_matches_created')
    op.drop_column('events', 'cup_leagues_created')
    op.drop_column('events', 'is_next')
    op.drop_column('events', 'is_current')
    op.drop_column('events', 'is_previous')
    op.drop_column('events', 'highest_score')
    op.drop_column('events', 'deadline_time_game_offset')
    op.drop_column('events', 'deadline_time_epoch')
    op.drop_column('events', 'highest_scoring_entry')
    op.drop_column('events', 'data_checked')
    op.drop_column('events', 'finished')
    op.drop_column('events', 'average_entry_score')
    op.drop_column('events', 'release_time')
    op.drop_index(op.f('ix_player_predictions_prediction_run_id'), table_name='player_predictions')
    op.drop_index(op.f('ix_player_predictions_player_id'), table_name='player_predictions')
    op.drop_index(op.f('ix_player_predictions_event_id'), table_name='player_predictions')
    op.drop_table('player_predictions')
    op.drop_table('prediction_runs')
    op.drop_table('phases')
    op.drop_table('element_types')
    op.drop_table('chips')
    # ### end Alembic commands ###
