"""store player gameweek statistics

Revision ID: 34a92ea96f15
Revises: af5cab389881
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '34a92ea96f15'
down_revision: Union[str, Sequence[str], None] = 'af5cab389881'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_gameweek_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('opponent_team_id', sa.Integer(), nullable=True),
    sa.Column('was_home', sa.Boolean(), nullable=True),
    sa.Column('kickoff_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('starts', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('goals_scored', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('clean_sheets', sa.Integer(), nullable=True),
    sa.Column('goals_conceded', sa.Integer(), nullable=True),
    sa.Column('own_goals', sa.Integer(), nullable=True),
    sa.Column('penalties_saved', sa.Integer(), nullable=True),
    sa.Column('penalties_missed', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.Column('bps', sa.Integer(), nullable=True),
    sa.Column('influence', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('creativity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('threat', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ict_index', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('clearances_blocks_interceptions', sa.Integer(), nullable=True),
    sa.Column('recoveries', sa.Integer(), nullable=True),
    sa.Column('tackles', sa.Integer(), nullable=True),
    sa.Column('defensive_contribution', sa.Integer(), nullable=True),
    sa.Column('expected_goals', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('expected_assists', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('expected_goal_involvements', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('expected_goals_conceded', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('transfers_balance', sa.Integer(), nullable=True),
    sa.Column('selected', sa.Integer(), nullable=True),
    sa.Column('transfers_in', sa.Integer(), nullable=True),
    sa.Column('transfers_out', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False, server_default='{}'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'gameweek', 'fixture_id', name='uq_player_gameweek_fixture_stat')
    )
    op.create_index(op.f('ix_player_gameweek_stats_fixture_id'), 'player_gameweek_stats', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_player_gameweek_stats_gameweek'), 'player_gameweek_stats', ['gameweek'], unique=False)
    op.create_index(op.f('ix_player_gameweek_stats_opponent_team_id'), 'player_gameweek_stats', ['opponent_team_id'], unique=False)
    op.create_index(op.f('ix_player_gameweek_stats_player_id'), 'player_gameweek_stats', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_gameweek_stats_player_id'), table_name='player_gameweek_stats')
    op.drop_index(op.f('ix_player_gameweek_stats_opponent_team_id'), table_name='player_gameweek_stats')
    op.drop_index(op.f('ix_player_gameweek_stats_gameweek'), table_name='player_gameweek_stats')
    op.drop_index(op.f('ix_player_gameweek_stats_fixture_id'), table_name='player_gameweek_stats')
    op.drop_table('player_gameweek_stats')
    # ### end Alembic commands ###
