"""add historical season tables

Revision ID: ade2d8127f58
Revises: 34a92ea96f15
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ade2d8127f58'
down_revision: Union[str, Sequence[str], None] = '34a92ea96f15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_player_gameweek_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('player_key', sa.String(length=100), nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('opponent_short_name', sa.String(length=10), nullable=True),
    sa.Column('was_home', sa.Boolean(), nullable=True),
    sa.Column('kickoff_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('starts', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('goals_scored', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('clean_sheets', sa.Integer(), nullable=True),
    sa.Column('goals_conceded', sa.Integer(), nullable=True),
    sa.Column('expected_goals', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('expected_assists', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('expected_goal_involvements', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('expected_goals_conceded', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'player_key', 'gameweek', 'fixture_id', name='uq_historical_player_gameweek_fixture')
    )
    op.create_index(op.f('ix_historical_player_gameweek_stats_gameweek'), 'historical_player_gameweek_stats', ['gameweek'], unique=False)
    op.create_index(op.f('ix_historical_player_gameweek_stats_player_key'), 'historical_player_gameweek_stats', ['player_key'], unique=False)
    op.create_index(op.f('ix_historical_player_gameweek_stats_season'), 'historical_player_gameweek_stats', ['season'], unique=False)
    op.create_table('historical_players',
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('player_key', sa.String(length=100), nullable=False),
    sa.Column('web_name', sa.String(length=100), nullable=False),
    sa.Column('team_short_name', sa.String(length=10), nullable=False),
    sa.Column('element_type', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('season', 'player_key')
    )
    op.create_table('historical_teams',
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=False),
    sa.Column('strength_overall_home', sa.Integer(), nullable=True),
    sa.Column('strength_overall_away', sa.Integer(), nullable=True),
    sa.Column('strength_attack_home', sa.Integer(), nullable=True),
    sa.Column('strength_attack_away', sa.Integer(), nullable=True),
    sa.Column('strength_defence_home', sa.Integer(), nullable=True),
    sa.Column('strength_defence_away', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('season', 'short_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historical_teams')
    op.drop_table('historical_players')
    op.drop_index(op.f('ix_historical_player_gameweek_stats_season'), table_name='historical_player_gameweek_stats')
    op.drop_index(op.f('ix_historical_player_gameweek_stats_player_key'), table_name='historical_player_gameweek_stats')
    op.drop_index(op.f('ix_historical_player_gameweek_stats_gameweek'), table_name='historical_player_gameweek_stats')
    op.drop_table('historical_player_gameweek_stats')
    # ### end Alembic commands ###
