"""retain complete bootstrap snapshots

Revision ID: af5cab389881
Revises: 122f67888406
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'af5cab389881'
down_revision: Union[str, Sequence[str], None] = '122f67888406'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bootstrap_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bootstrap_snapshots')
    # ### end Alembic commands ###
