"""add match odds tables

Revision ID: dbd20f1e3c63
Revises: ade2d8127f58
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dbd20f1e3c63'
down_revision: Union[str, Sequence[str], None] = 'ade2d8127f58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_match_odds',
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('home_short_name', sa.String(length=10), nullable=False),
    sa.Column('away_short_name', sa.String(length=10), nullable=False),
    sa.Column('home_win_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('draw_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('away_win_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('over_2_5_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('under_2_5_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('season', 'home_short_name', 'away_short_name')
    )
    op.create_table('match_odds',
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('home_win_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('draw_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('away_win_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('over_2_5_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('under_2_5_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('fixture_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_odds')
    op.drop_table('historical_match_odds')
    # ### end Alembic commands ###
